image: alpine:latest

before_script:
  - echo "$SSH_KNOWN_HOSTS"
  - 'which ssh-agent || ( apk add --update openssh )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


  
cache:
  paths:
    - /cache

stages:
  - deploy
  
deploy-trending:
  stage: deploy
  script:
    - ssh trending@192.168.9.92 ./deploy.sh