# params.py

PARAMS_CONFIG = {
    'DELTA_TIME_RUSHHOUR': 5 * 60,
    'DELTA_TIME_NORMALHOUR': 15 * 60,
    'VIEW_PIVOT_RUSHHOUR': 3,
    'VIEW_PIVOT_NORMALHOUR': 1,
    'LIKE_VIEW_RUSHHOUR': 5,
    'LIKE_VIEW_NORMALHOUR': 2,
    'STORAGE_TIME': 24 * 60 * 60,
    'DAILY_PIVOT': 0
}

PARAMS = {
    'HALFLIFE': 2 * 60 * 60,
    'SMOOTHING': 3.0,
    'DELTA_TIME': 15 * 60
}
